### ISSUE TITLE
Discord does not connect, and no prompt is triggered even with popup enabled

### ISSUE THREAD

**Issue by Emralegna** [deminimis/minimalfirewall#68]
Hello,

Once lockdown mode is enabled Discord can’t connect at all and MinimalFirewall won’t prompt for it even if popup are enabled.

Its default shortcut (also for startup entry) launches '%AppData%\Local\Discord\Update.exe --processStart Discord.exe' and it seems that MinimalFirewall doesn’t catches it

If Discord is already launched, it disconnects it.

Thanks for your support.

**Comment by deminimis** [comment]
Thank you, I'll look into it. I just released [version 2.6](https://github.com/deminimis/minimalfirewall/releases), but I didn't see this before releasing.

**Comment by Emralegna** [comment]
I tested just now and the issue persists.
Oddly. an app that does not have rules like Firefox (saying it could not connect to the DNS server), has not been prompted either, but some has like SSDPSRV and netprofm (which are svchosts services) did.

**Comment by Emralegna** [comment]
Unfortunately it has not fixed the issue

If you have an idea about how I can help further let me know

**Comment by Emralegna** [comment]
It still didn’t work, even with the new version 2.6.3

I deleted all the rules, then rebooted, and it finally asked for 'discord.exe' after a few minutes.

But, its parent process 'update.exe' is still not asking for it, and since it launch discord by this process (all shortcuts it installs invoke update.exe first), it does not connect saying 'Update failed'.

It also asked for Edge but not for Firefox.

Some other does not work either, like Windows Update. It does not ask for the process responsible for it and  with 'Auto-allow apps trusted by Windows' it still fails when ticked

Sorry for all the bother :/

**Comment by deminimis** [comment]
> I’m running Windows 11 25H2 Enterprise (not LTSC or such) fully up to date 'upgraded' from Pro to test it out of curiosity, then stuck with it because my Pro key was not working anymore afterward.
> 
> I’m not using any script or tools to tweak Windows Defender, but I’ve enabled everything I could for security in its settings
> 
> I’ve installed DotNet 8.0.22 and 9.0.11
> 
> By debug you meant exporting diagnostic package ? If so :
> 
> [mfw_diagnostics_20251125_122756.zip](https://github.com/user-attachments/files/23745632/mfw_diagnostics_20251125_122756.zip)
> 
> Oddly, in debug_log_last1500.txt it says 'debug_log.txt not found.'
> 
> In %AppData% the folder is empty

Sorry, there is another switch above, to turn on debugging.

**Comment by herrenP** [comment]
> [version 2.7.1](https://github.com/deminimis/minimalfirewall/releases/) works for me for WSL. Please check WSL and Discord to see if they are working for you.

Sorry for super late reply. I tried 2.7.1 without any luck. Also, I think that version either has the wrong .exe or it's tag was never updated since the program says "2.7.0" in "Settings".

Anyway, I tried 2.7.4 and now I get popups. Thanks!
