### ISSUE TITLE
Create New Rule Error

### ISSUE THREAD

**Issue by se-co-de** [deminimis/minimalfirewall#71]
MF 2.6 on Windows 10 Home 22H2.

Rules > Create New Rule > Allow or Block a Program

Always gives an Error (in debug_log.txt):

ERROR BackgroundTask-ApplyApplicationRule ArgumentException HResult=0x80070057 Message=Value does not fall within the expected range.

**Comment by deminimis** [comment]
Fixed in [version 2.6.1](https://github.com/deminimis/minimalfirewall/releases/tag/v2.6.1).

**Comment by se-co-de** [comment]
MF 2.6.1

This issue persists when creating a rule via the alert pop-up.

Same error as in above comment

**Comment by se-co-de** [comment]
MF 2.6.2 on Windows 10 Home 22H2

This issue persists when creating a rule via the alert pop-up OR when manually creating a rule via the wizard.

The rule is not created, and does not appear in the Rules list page.

I tried to create 'Allow' rules for:

Brave
Chrome
Edge
Firefox

All permanently blocked from internet.

I had to roll back to MF 2.5.5 to access the internet to leave a message here!


MF 2.6.2 ERROR:

[2025-11-21 17:10:39] [Cache] Invalidated MFW Rules cache after task: CreateAdvancedRule
[2025-11-21 17:10:39] Processing Pending Connection for 'C:\program files\bravesoftware\brave-browser\application\brave.exe'. Decision: Allow, Duration: 00:00:00, Trust Publisher: False
[2025-11-21 17:10:39] Creating Application Rule: 'brave - Out' for 'C:\program files\bravesoftware\brave-browser\application\brave.exe'
[2025-11-21 17:10:39] [Rule Debug] Starting creation for rule: brave - Out
[2025-11-21 17:10:39] ERROR [FATAL] CreateSingleAdvancedRule failed for 'brave - Out' ArgumentException HResult=0x80070057 Message=Value does not fall within the expected range.
[2025-11-21 17:10:39] ERROR BackgroundTask-ProcessPendingConnection ArgumentException HResult=0x80070057 Message=Value does not fall within the expected range.

**Comment by se-co-de** [comment]
Windows 10 Home 22H2, all updates.

Yes, Debug2.6 seems to work ok creating and saving new rules.

**Comment by deminimis** [comment]
Fixed in  [version 2.6.3](https://github.com/deminimis/minimalfirewall/releases).
